# Change these first
owner: fernanfs # Your GitHub organization or username, where this repository lives
repo: www.pdfa.org-monitoring # The name of this repository

sites:
  - name: PDF Association
    url: https://www.pdfa.org
  - name: PDFA Association, Inc.
    url: https://pdfa-inc.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.pdfa.org
  baseUrl: /www.pdfa.org-monitoring
  logoUrl: https://www.pdfa.org/wp-content/uploads/2018/12/pdf-association-logo-300x141.png
  name: PDF Association Status
  introTitle: "Service Status Overview"
  introMessage: "This is an overview of the PDF Association pages and their respective status."
  navbar:
    - title: Status
      href: /
    - title: www.pdfa.org
      href: https://www.pdfa.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
